export const SET_ACCOUNT_ID = "SET_ACCOUNT_ID";
export const GET_BALANCES = "GET_BALANCES";
export const GET_BALANCES_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCES_ERROR = "GET_BALANCES_ERROR";