export const SET_SEED = "SET_SEED";

export const GET_ACCOUNT = "GET_ACCOUNT";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_ERROR = "GET_ACCOUNT_ERROR";

export const SEND_PAYMENT = "SEND_PAYMENT";
export const SEND_PAYMENT_SUCCESS = "SEND_PAYMENT_SUCCESS";
export const SEND_PAYMENT_ERROR = "SEND_PAYMENT_ERROR";